AppWebHotelBeach/Controllers/PaqueteController.cs
using ApiHotelBeach.Models;
using AppWebHotelBeach.Models;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace AppWebHotelBeach.Controllers
{
    public class PaqueteController : Controller
    {
        private static readonly HttpClient client = new HttpClient();
        private static string direccionAPI = "https://localhost:7125/api/paquetes";

        //Views
        [HttpGet]
        public async Task<IActionResult> Index()
        {           
                var paquetes = await extraerPaquetes();
                return View(paquetes);                       
           
        }

        //-----------------------------------------------------------------

        private async Task<List<Paquete>> extraerPaquetes()
        {
            try
            {
                HttpResponseMessage response = await client.GetAsync(direccionAPI);

                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync().Result;
                    var paquetes = JsonConvert.DeserializeObject<List<Paquete>>(result);
                    return paquetes;
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return null;
        }

        private async Task<Cliente> extraerPaquetes(int id)
        {
            try
            {
                HttpResponseMessage response = await client.GetAsync(direccionAPI + "/" + id);

                if (response.IsSuccessStatusCode)
                {
                    var result = response.Content.ReadAsStringAsync().Result;
                    var cliente = JsonConvert.DeserializeObject<Cliente>(result);
                    return cliente;
                }
            }
            catch (Exception ex)
            {
                throw;
            }
            return null;
        }
    }
}

AppWebHotelBeach/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AppWebHotelBeach</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/AppWebHotelBeach.styles.css" asp-append-version="true" />

    <!--- <title>Alert Box | CodingLab </title>----->
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css" />

</head>
<body class="FondoInicio">
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark box-shadow mb-3  barra">
            <div class="container-fluid">
                <a class="navbar-brand" tyle="font-size: 20px" asp-area="" asp-controller="Home" asp-action="Index">AppWebHotelBeach</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        

                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                            <a class="nav-link fas fa-book border-start" asp-area="" asp-controller="Reserva" asp-action="Create">   Reservar</a>
                            </li>                          
                        }
                        else
                        {
                            <li class="nav-item">
                            <a class="nav-link fas fa-book border-start" asp-area="" asp-controller="Cliente" asp-action="Login">   Reservar</a>
                            </li> 
                        }                                                                 
                        <li class="nav-item">
                            <a class="nav-link fas fa-bed border-start" asp-area="" asp-controller="Paquete" asp-action="Index">   Paquetes</a>
                        </li>





                        <li class="nav-item">
                            <a class="nav-link fas fa-user border-start" asp-area="" asp-controller="Cliente" asp-action="Index">   Mantenimiento Clientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link fas fa-gift border-start " asp-area="" asp-controller="Reserva" asp-action="Index">   Mantenimiento Paquetes</a>
                        </li>






                        <li class="nav-item">
                            <a class="nav-link fas fa-eye border-start" asp-area="" asp-controller="Home" asp-action="Privacy">   Privacy</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav" id="MenuSeguridad">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item" style="padding-right:2ex">
                                <a class="btn Botones" asp-area="" asp-controller="" asp-action="">
                                    Hola @User.Identity.Name
                                </a>
                            </li>


                            <li class="nav-item">
                                <a class="btn Botones fas fa-sign-out" asp-area="" asp-controller="Cliente" asp-action="Logout">
                                       Cerrar Sesion
                                </a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="btn Botones fas fa-user-plus" asp-area="" asp-controller="Cliente" asp-action="Login">
                                       Iniciar Sesion
                                </a>
                            </li>
                        }

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted Textos" style=" background: rgba(216, 243, 220, 70%)">
        <div class="container">
            &copy; 2023 - AppWebHotelBeach - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>